### ISSUE TITLE
Adding Limit Option per User

### ISSUE THREAD

**Issue by irfanfadilah** [hubot-scripts/hubot-google-images#27]
Hi, I wonder if it's possible to add such feature, because some people don't want to get flooded with the others who keep issuing Hubot to "image me" or "animate me" in some channels.

The idea is limiting a user from keep issuing those commands, like quota request per day, then in the next day the quota will be reset to zero.

I wrote a code to use HubotBrain to store the data for users (https://gist.github.com/irfanfadilah/2c46208eb4dcb2f03d05) but not sure how to integrate it to Google Images Script.

* the Gist is for Slack adapter and using Heroku + Redis.

So what do you think guys?

**Comment by HaroldPutman** [comment]
Since it could apply to other commands, this sounds like something that would best be handled as middleware (https://github.com/github/hubot/blob/master/docs/scripting.md#middleware) rather than integrated into hubot-google-images.

Or simply apply some social pressure to the offending user `@hubot image me We're all trying to work and this is annoying`   ;-)

**Comment by technicalpickles** [comment]
This probably could be done as a response middleware now that we have that. Don't allow hubot to `msg.send` more than 5-10 messages at once, for example.

That said, I've seen it implemented in nearly every "post an image or several" script" I've come across. It's pretty easy to add.
